// review exercise 01 - generating pseudorandom numbers
#include <iostream>
#include <cstdlib>

int main()
{
    using namespace std;
    srand(2);
    // srand() gives a seed that determines the sequence of numbers
    // generated by rand()

    cout << "Gerando números pseudoaleatórios:\n";
    cout << rand() << " ";
    cout << rand() << " ";
    cout << rand() << " ";
    cout << rand() << " ";
    cout << rand() << endl;

    return 0;
}
